builds:
  -
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - 386
      - amd64
      - arm
      - arm64
archive:
  format_overrides:
      - goos: windows
        format: zip